version: "2.4" # single host

services:
  minecraft:
    container_name: minecraft
    network_mode: bridge
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    environment:
      # infra
      MEMORY: "16G"
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "true"
      SERVER_NAME: "Pepe Muakzz You"
      STOP_SERVER_ANNOUNCE_DELAY: "600" # 10 minutes
      STOP_DURATION: "60" # 1 minute
      ENABLE_RCON: "true"
      RCON_PASSWORD: "pepeloveyou123" # edit after initiation
      RCON_PORT: 25575
      OVERRIDE_SERVER_PROPERTIES: "true"
      DUMP_SERVER_PROPERTIES: "true"
      MAX_TICK_TIME: "-1"
      # base game
      VERSION: 1.21.5
      # SEED: "1171653971640638092"
      MAX_WORLD_SIZE: 5000
      TZ: "Asia/Kuala_Lumpur"
      MOTD: "Muakzz"
      DIFFICULTY: "normal"
      MODE: "survival"
      # ICON: "data/icon.png"
      # OVERRIDE_ICON: "true"
      # gameplay
      ENABLE_QUERY: "true"
      ALLOW_NETHER: "true"
      GENERATE_STRUCTURES: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      # fabric
      EULA: "TRUE"
      TYPE: "FABRIC"
      FABRIC_LAUNCHER_VERSION: 1.0.3
      FABRIC_LOADER_VERSION: 0.16.13
      # Since Fabric server type only includes the loader, most times
      # the fabric-api is required for other mods to function
      MODRINTH_PROJECTS: |
        fabric-api
        terralith
        vanilla-refresh
      # player
      MAX_PLAYERS: 24
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      VIEW_DISTANCE: 10
      SIMULATION_DISTANCE: 10
      PLAYER_IDLE_TIMEOUT: 0

    ports:
      - "25565:25565" # minecraft server port
      - "25575:25575" # rcon port
    volumes:
      - "./data:/data"
      - "./mods:/mods" # for fabric mods

  # backups:
  #   image: itzg/mc-backup:2025.4.0
  #   user: "1000"
  #   depends_on:
  #     mc:
  #       condition: service_healthy
  #   environment:
  #     BACKUP_METHOD: rsync
  #     PRUNE_BACKUPS_COUNT: 50
  #     PRUNE_BACKUPS_DAYS: 5000
  #     BACKUP_INTERVAL: "2h"
  #     RCON_HOST: mc
  #     # since this service waits for mc to be healthy, no initial delay is needed
  #     INITIAL_DELAY: 0
  #     # As an example, to backup only the world data:
  #     # INCLUDES: world,world_nether,world_the_end
  #   volumes:
  #     - ./data:/data:ro
  #     - ./backups:/backups
