services:
  minecraft:
    container_name: minecraft
    network_mode: bridge
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    environment:
      # infra
      MEMORY: "16G"
      ENABLE_ROLLING_LOGS: "true"
      ONLINE_MODE: "true"
      SERVER_NAME: "Pepe Muakzz You"
      STOP_SERVER_ANNOUNCE_DELAY: "600" # 10 minutes
      STOP_DURATION: "60" # 1 minute
      ENABLE_RCON: "true"
      RCON_PASSWORD: "pepeloveyou123" # edit after initiation
      RCON_PORT: 25575
      OVERRIDE_SERVER_PROPERTIES: "true"
      DUMP_SERVER_PROPERTIES: "true"
      MAX_TICK_TIME: "-1"
      # base game
      VERSION: 1.21.5
      SEED: "7145097980"
      MAX_WORLD_SIZE: 10000
      TZ: "Asia/Kuala_Lumpur"
      MOTD: "Muakzz"
      DIFFICULTY: "normal"
      MODE: "survival"
      PAUSE_WHEN_EMPTY_SECONDS: 10
      # ICON: "data/icon.png"
      # OVERRIDE_ICON: "true"
      # gameplay
      ENABLE_QUERY: "true"
      ALLOW_NETHER: "true"
      GENERATE_STRUCTURES: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      ALLOW_FLIGHT: "true"
      # fabric
      EULA: "TRUE"
      TYPE: "FABRIC"
      FABRIC_LAUNCHER_VERSION: 1.0.3
      FABRIC_LOADER_VERSION: 0.16.13
      # Since Fabric server type only includes the loader, most times
      # the fabric-api is required for other mods to function
      MODRINTH_PROJECTS: |
        fabric-api
        vanilla-refresh
        villager-in-a-bucket
        appleskin
      CUSTOM_SERVER_PROPERTIES: |
        custom1=value1
      # player
      MAX_PLAYERS: 24
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      VIEW_DISTANCE: 10
      SIMULATION_DISTANCE: 10
      PLAYER_IDLE_TIMEOUT: 0
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "true"
      EXISTING_WHITELIST_FILE: "SYNC_FILE_MERGE_LIST"
      WHITELIST_FILE: "/players/whitelist.json"
      OVERRIDE_OPS: "true"
      EXISTING_OPS_FILE: "SYNC_FILE_MERGE_LIST"
      OPS_FILE: "/players/ops.json"

    ports:
      - "25565:25565" # minecraft server port
      - "25575:25575" # rcon port
    volumes:
      - "./data:/data"
      - "./mods:/mods" # for fabric mods
      - "./players:/players"

  backup_agent:
    build:
      context: ./backup_agent
      dockerfile: ./Dockerfile 
    container_name: minecraft-backup
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
      # system level
      SYS_LOG_LEVEL: "INFO"
      ENABLE_DISCORD_LOGGING: "true"
      DISCORD_LOG_LEVEL: "ERROR"
      # please make sure to export this variable in your shell that contains the json key "discord_webhook_url"
      SECRET_ID: ${SECRET_ID}
      ENVIRONMENT: "production"
      # app level
      FILE_PREFIX: "backup"
      FILE_SUFFIX_TIMESTAMP_FORMAT: "%Y%m%dT%H%M%S"
      TARGET_PATH: "/backups"
      SOURCE_PATH: "/data/world"
      BUCKET_NAME: "bucket-minecraft-backups"
      BUCKET_PREFIX: "backup"
      RETENTION_COUNT: 10 # number of backups to keep
      CRON_SCHEDULE: "0 2 * * *" # runs daily at 2 AM
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
    restart: unless-stopped
